name: Generate SHA badge 2
on:
  push:
    branches:
      - master
      - production
      - canary
jobs:
  badge_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: shields-badges

      - name: Compute Payload
        id: payload
        run: |
          echo "short_hash=$(git rev-parse --short $GITHUB_SHA)" >> $GITHUB_OUTPUT

      - name: Create Badge
        uses: emibcn/badge-action@v2.0.2
        with:
          label: ${{ github.ref_name }} SHA
          status: ${{ steps.payload.outputs.short_hash }}
          color: blue
          path: ${{ github.ref_name }}-sha.svg

#      - name: Commit Badge
#        run: |
#          git config --global user.email "sha-badge-bot@github.com"
#          git config --global user.name "SHA badge bot"
#          git add .
#          git commit -m "Add/Update ${{ github.ref_name }}-sha.svg"
#          git push origin shields-badges

      - name: Commit Badge
        uses: EndBug/add-and-commit@v9
        with:
          message: Add/Update ${{ github.ref_name }}-sha.svg
